general.import = [

  "/usr/lib/node_modules/alacritty-themes/themes/Catppuccin-Mocha.toml"
]

[window]
decorations = "none"
startup_mode = "Maximized"
  [window.padding]
  x = 10
  y = 10

[font]
size = 12

  [font.bold]
  family = "JetBrainsMono Nerd Font"
  style = "Bold"

  [font.bold_italic]
  family = "JetBrainsMono Nerd Font"
  style = "Bold Italic"

  [font.italic]
  family = "JetBrainsMono Nerd Font"
  style = "Italic"

  [font.normal]
  family = "JetBrainsMono Nerd Font"
  style = "Regular"

[env]
TERM = "xterm-256color"

[cursor]
blink_timeout = 0

  [cursor.style]
  blinking = "Always"
