icons_format = "{icon}"

[theme]
theme = "ctp-latte"
[theme.overrides]
idle_bg = "#1a1b26"    # Background
idle_fg = "#c0caf5"    # Foreground (text)

# Link good/warning colors to look consistent
good_fg = { link = "warning_fg" }
good_bg = { link = "warning_bg" }
warning_fg = { link = "good_fg" }
warning_bg = { link = "good_bg" }

[icons]
icons = "awesome4"

[[block]]
block = "battery"
full_format = " $icon $percentage "
charging_format = " $icon $percentage 󱐋 "
[block.theme_overrides]
good_bg = "#9ece6a"    # Green (Charging/Full battery)
good_fg = "#1a1b26"    # Contrast text
idle_bg = "#9ece6a"
idle_fg = "#1a1b26"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"
[block.theme_overrides]
idle_bg = "#bb9af7"    # Purple
idle_fg = "#1a1b26"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
[block.theme_overrides]
idle_bg = "#7aa2f7"    # Blue
idle_fg = "#1a1b26"
