icons_format = "{icon}"

[theme]
theme = "gruvbox-dark"

[theme.overrides]
idle_bg = "#1F1F28" # sumiInk1
idle_fg = "#DCD7BA" # oldWhite

# Kanagawa status colors
good_bg = "#76946A" # autumnGreen
good_fg = "#1F1F28" # sumiInk1

warning_bg = "#C0A36E" # roninYellow
warning_fg = "#1F1F28" # sumiInk1

info_bg = "#7E9CD8" # crystalBlue
info_fg = "#1F1F28" # sumiInk1

critical_bg = "#E82424" # springCrimson
critical_fg = "#DCD7BA" # oldWhite

[icons]
icons = "awesome4"

[[block]]
block = "battery"
full_format = " $icon $percentage "
charging_format = " $icon $percentage 󱐋 "

[block.theme_overrides]
good_bg = "#76946A" # autumnGreen
good_fg = "#1F1F28" # sumiInk1
idle_bg = "#76946A"
idle_fg = "#1F1F28"
warning_bg = "#C0A36E" # roninYellow
warning_fg = "#1F1F28"
critical_bg = "#E82424" # springCrimson
critical_fg = "#DCD7BA"

[[block]]
block = "sound"

[[block.click]]
button = "left"
cmd = "pavucontrol"

[block.theme_overrides]
idle_bg = "#938AA9" # oniViolet
idle_fg = "#1F1F28"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "

[block.theme_overrides]
idle_bg = "#7E9CD8" # crystalBlue
idle_fg = "#1F1F28"
