# Tab navigation
unbind -n M-1
unbind -n M-2
unbind -n M-3
unbind -n M-4
unbind -n M-5
unbind -n M-6
unbind -n M-7
unbind -n M-8

# Pane navigation
unbind -n M-h
unbind -n M-j
unbind -n M-k
unbind -n M-l

unbind -n M-Left
unbind -n M-Down
unbind -n M-Up
unbind -n M-Right

# Split panes
unbind -n M-H
unbind -n M-V

# Windows
unbind -n M-c
unbind -n M-q
unbind -n M-J
unbind -n M-K

# Rename / Sessions
unbind -n M-r
unbind -n M-s

# Copy mode
unbind -n M-Space
unbind -T copy-mode-vi y
unbind -T copy-mode-vi Escape

# New session
unbind -n M-S

# Popup
# unbind -n M-t
