# ========== Core Settings ==========
unbind C-b
set -g prefix None 
set -g mouse on
set -g focus-events on
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:Tc"
set -g terminal-overrides ',*:kLFT5=\EL'
set -g base-index 1
set -g set-clipboard on
set -g detach-on-destroy off
set -g escape-time 0
set -g history-limit 1000000
set -g status-interval 3
set -g allow-passthrough on
set -g status-position top
setw -g mode-keys vi

# ========== Reload Config ==========
bind -n M-R source-file ~/dotfiles/tmux/.config/tmux/tmux.conf \; display-message "Reloaded!"

set -g @tabs_enabled 1
# enable keybinds by default
source-file ~/dotfiles/tmux/.config/tmux/tmux.keybinds-on.conf

# ========== Toggle Keybinds ==========
bind -n M-g run-shell '
if [ "#{@tabs_enabled}" = "1" ]; then
    tmux source-file ~/dotfiles/tmux/.config/tmux/tmux.keybinds-off.conf
    tmux set-option -g @tabs_enabled 0
else
    tmux source-file ~/dotfiles/tmux/.config/tmux/tmux.keybinds-on.conf
    tmux set-option -g @tabs_enabled 1
fi
'

# ========== Theme ==========
bg="#282828"
default_fg="#ebdbb2"
session_fg="#d79921"
session_selection_fg="#282828"
session_selection_bg="#d79921"
active_window_fg="#b8bb26"
active_pane_border="#504945"

set -g status-left-length 200
set -g status-right-length 200
set -g status-left "#[fg=${session_fg},bold,bg=${bg}]  #S #[fg=${default_fg},nobold,bg=${bg}]#{?@tabs_enabled,,🔒} | "
set -g status-justify left
set -g status-style "bg=${bg}"
set -g window-status-format "#[fg=${default_fg},bg=default] #I:#W"
set -g window-status-current-format "#[fg=${active_window_fg},bold,bg=default]  #[underscore]#I:#W"
set -g window-status-last-style "fg=${default_fg},bg=default"
set -g message-command-style "bg=default,fg=${default_fg}"
set -g message-style "bg=default,fg=${default_fg}"
set -g mode-style "bg=${session_selection_bg},fg=${session_selection_fg}"
set -g pane-active-border-style "fg=${active_pane_border},bg=default"
set -g pane-border-style "fg=#3b4261,bg=default"
