changequote([,])dnl
define([MOD], [M-])dnl
# Tab switching
bind -n MOD[1] select-window -t 1
bind -n MOD[2] select-window -t 2
bind -n MOD[3] select-window -t 3
bind -n MOD[4] select-window -t 4
bind -n MOD[5] select-window -t 5
bind -n MOD[6] select-window -t 6
bind -n MOD[7] select-window -t 7
bind -n MOD[8] select-window -t 8

# Pane navigation
bind -n MOD[h] select-pane -L
bind -n MOD[j] select-pane -D
bind -n MOD[k] select-pane -U
bind -n MOD[l] select-pane -R

# Arrow keys
bind -n MOD[Left]  select-pane -L
bind -n MOD[Down]  select-pane -D
bind -n MOD[Up]    select-pane -U
bind -n MOD[Right] select-pane -R

# Split panes
bind -n MOD[H] split-window -h
bind -n MOD[V] split-window -v

# New / close tabs
bind -n MOD[c] new-window
bind -n MOD[q] confirm-before -p "Close tab? (y/n)" kill-window

# Switch tabs
bind -n MOD[J] next-window
bind -n MOD[K] previous-window

# Rename session
bind -n MOD[r] command-prompt -I "#S" "rename-session '%%'"

# Show sessions
bind -n MOD[s] choose-session

# Copy mode
bind -n MOD[Space] copy-mode
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy"
bind -T copy-mode-vi Escape send -X cancel

# New session
bind -n MOD[S] new-session
# floating pane
bind -n MOD[p] display-popup -w 60% -h 60%

# TPM install
bind-key -n MOD[i] run-shell '~/.config/tmux/plugins/tpm/bin/install_plugins'
