# Tab switching
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8

# Pane navigation
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Arrow keys
bind -n M-Left  select-pane -L
bind -n M-Down  select-pane -D
bind -n M-Up    select-pane -U
bind -n M-Right select-pane -R

# Split panes
bind -n M-H split-window -h
bind -n M-V split-window -v

# New / close tabs
bind -n M-c new-window
bind -n M-q confirm-before -p "Close tab? (y/n)" kill-window

# Switch tabs
bind -n M-J next-window
bind -n M-K previous-window

# Rename session
bind -n M-r command-prompt -I "#S" "rename-session '%%'"

# Show sessions
bind -n M-s choose-session

# Copy mode
bind -n M-Space copy-mode
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy"
bind -T copy-mode-vi Escape send -X cancel

# New session
bind -n M-S new-session

# TPM install
bind-key -n M-i run-shell '~/.config/tmux/plugins/tpm/bin/install_plugins'
