#!/bin/sh

sleep 10

notify-send --urgency=low "Script Started" "Battery alert script is now running"

while true; do
    battery_status=$(cat /sys/class/power_supply/BAT0/status)
    battery_charge=$(cat /sys/class/power_supply/BAT0/capacity)

    if [[ "$battery_status" == "Discharging" ]]; then
        if [[ "$battery_charge" -le 15 ]]; then
            notify-send --urgency=critical "Battery critical!" "${battery_charge}%"
            sleep 180
        elif [[ "$battery_charge" -le 25 ]]; then
            notify-send --urgency=critical "Battery low!" "${battery_charge}%"
            sleep 240
        elif [[ "$battery_charge" -le 40 ]]; then
            notify-send "Battery low" "${battery_charge}%"
            sleep 360
        elif [[ "$battery_charge" -le 60 ]]; then
            notify-send "Battery notice" "${battery_charge}%"
            sleep 600
        else
            sleep 600
        fi
    else
        sleep 600
    fi
done
