require("custom.keymaps")
require("custom.options")
require("lsp")
require("custom.macro")

require("vim._core.ui2").enable({})
-- plugins
vim.cmd.packadd("nvim.undotree")
vim.cmd.packadd("nvim.difftool")
require("plugins.mini")
require("plugins.fuzzy")
require("plugins.colorscheme")
require("plugins.gitsigns")
require("plugins.compile-mode")
require("plugins.md")
require("plugins.multi-cursor")
require("plugins.todo-comment")
require("plugins.treesitter")
require("plugins.neotest")
require("plugins.comfy-line-nums")
require("plugins.completion")
require("plugins.harpoon")
require("plugins.luasnip")
require("plugins.conform")
