require("config.lazy")
require("config.options")
require("config.keymaps")
vim.cmd("colorscheme kanagawa")
Enable_transparency()
vim.api.nvim_set_hl(0, "cursorline", { ctermbg = "darkgray", bg = "#262626" })
