bar {
    status_command i3status-rs
    mode hide
    modifier $mod
    font pango:JetBrainsMono Nerd Font, FontAwesome 12
	colors {
		separator            #54546D
		background           #1F1F28
		statusline           #DCD7BA
		focused_workspace    #7E9CD8 #7E9CD8 #1F1F28
		active_workspace     #2A2A37 #2A2A37 #DCD7BA
		inactive_workspace   #2A2A37 #2A2A37 #727169
		urgent_workspace     #E82424 #E82424 #DCD7BA
	}
}
