default_border pixel 2
default_floating_border pixel 2
hide_edge_borders smart

input "type:touchpad" {
    dwt enabled
    tap enabled
    middle_emulation enabled
    natural_scroll enabled
    drag enabled
    drag_lock disabled
}

input "type:mouse" {
    pointer_accel 0.5
}

input "type:keyboard" {
    # xkb_layout us,iq
    # xkb_options grp:alt_shift_toggle
    repeat_rate 50
    repeat_delay 250
}

output * bg ./wallpaper.jpg fill

# for_window [app_id=".*"] border none
