default_border pixel 2
default_floating_border pixel 2
hide_edge_borders smart
output eDP-1 scale 1.2
input "type:touchpad" {
	# pointer_accel 0.2
    dwt 		     enabled
    tap              enabled
    middle_emulation enabled
    natural_scroll   enabled
}

input "type:mouse" {
    pointer_accel 0.5
}

input "type:keyboard" {
    # xkb_layout us,iq
    # xkb_options grp:alt_shift_toggle
    repeat_rate 50
    repeat_delay 250
}

output * bg ./wallpaper.jpg fill
for_window [app_id="com.gabm.satty"] {
	floating enable
	resize set width 1432 px height 718 px
	move position center
	border 10
}

# for_window [app_id=".*"] border none
